//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FW_TrackIn_RMSWebService.FW_TrackIn_RMSWebServiceSoap")]
    public interface FW_TrackIn_RMSWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RMSTrackIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.TrackIn RMSTrackIn(string FWLotID, string FWMachID, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RMSTrackIn", ReplyAction="*")]
        System.Threading.Tasks.Task<Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.TrackIn> RMSTrackInAsync(string FWLotID, string FWMachID, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RMSDeleteJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.DeleteJob RMSDeleteJob(string RMSJobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RMSDeleteJob", ReplyAction="*")]
        System.Threading.Tasks.Task<Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.DeleteJob> RMSDeleteJobAsync(string RMSJobID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TrackIn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteJob : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FW_TrackIn_RMSWebServiceSoapChannel : Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.FW_TrackIn_RMSWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FW_TrackIn_RMSWebServiceSoapClient : System.ServiceModel.ClientBase<Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.FW_TrackIn_RMSWebServiceSoap>, Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.FW_TrackIn_RMSWebServiceSoap {
        
        public FW_TrackIn_RMSWebServiceSoapClient() {
        }
        
        public FW_TrackIn_RMSWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FW_TrackIn_RMSWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FW_TrackIn_RMSWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FW_TrackIn_RMSWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.TrackIn RMSTrackIn(string FWLotID, string FWMachID, string UserID) {
            return base.Channel.RMSTrackIn(FWLotID, FWMachID, UserID);
        }
        
        public System.Threading.Tasks.Task<Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.TrackIn> RMSTrackInAsync(string FWLotID, string FWMachID, string UserID) {
            return base.Channel.RMSTrackInAsync(FWLotID, FWMachID, UserID);
        }
        
        public Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.DeleteJob RMSDeleteJob(string RMSJobID) {
            return base.Channel.RMSDeleteJob(RMSJobID);
        }
        
        public System.Threading.Tasks.Task<Qynix.EAP.Drivers.SOAPRequestDriver.FW_TrackIn_RMSWebService.DeleteJob> RMSDeleteJobAsync(string RMSJobID) {
            return base.Channel.RMSDeleteJobAsync(RMSJobID);
        }
    }
}
